output_dir: ~/scratch/experiments/

dataset:
  class: WN18RRInductive
  path: ~/kg-datasets/
  version: {{ version }}

task:
  class: InductiveKnowledgeGraphCompletion
  model:
    class: NBFNet
    base_layer:
      class: NBFNetConv
      input_dim: 32
      output_dim: 32
      query_input_dim: 32
      message_func: distmult
      aggregate_func: pna
      layer_norm: yes
      dependent: no
    num_layer: 6
    short_cut: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32

train:
  num_epoch: 20

metric: mrr